name: Publish On NPMJS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: https://registry.npmjs.org/

    - name: Set Git Config
      run: |
        git config --global user.email "ci-build@aemforms"
        git config --global user.name "ci-build"
      env:
        GITHUB_TOKEN: ${{ secrets.ADOBE_GH_TOKEN }}
        GH_TOKEN: ${{ secrets.ADOBE_GH_TOKEN }}

    - name: Install dependencies
      run: npm install

    - name: Build theme
      run: npm run build
  
    - name: Authenticate with NPM Registry
      run: |
        echo "registry=https://registry.npmjs.org/" >> .npmrc
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        npm whoami
      env:
        NPM_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}

    - name: Discard Uncommitted Changes
      run: git reset --hard

    - name: Get current version
      id: get_version
      run: echo ::set-output name=version::$(node -p "require('./package.json').version")

    - name: Bump version
      id: bump_version
      run: |
        npm version patch -m "Bump version to %s"
    
    - name: Backup original package.json
      run: cp package.json package.json.bak

    - name: Modify package.json for scoped publish
      run: |
        jq '.name = "@aemforms/af-healthcare-theme"' package.json > package.json.tmp && mv package.json.tmp package.json

    - name: Publish to npm
      run: |
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}

    - name: Restore original package.json
      run: mv package.json.bak package.json

    - name: Push changes to remote repository
      run: git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.ADOBE_GH_TOKEN }}
        GH_TOKEN: ${{ secrets.ADOBE_GH_TOKEN }}
